
var errorCode = {

	SUCCESS:0,

	//CreateRoom
	CREATE_FAILD:1001,//参数错误
	ROOM_CONF_IS_NULL:1002,//房间配置是空的
	ROOM_TYPE_NOT_MATCH:1003,//房间类型不匹配
	DIAMOND_NOT_ENOUGH:1004,//钻石不足

	//JoinRoom
	ROOM_NOT_EXIST:1101,//房间不存在

	//login
	INVALID_PARAMETERS:9000,//登陆参数不足
	INVALID_SING:9001,//登陆参数不合法
	TOKEN_OUT_OF_TIME:9002,//token超时，不合法

	//club
	CLUB_CREATE_MAX_LIMIT:1200,//创建俱乐部数量超过限制
	CLUB_CREATE_NO_NAME:1201,//没名字
	CLUB_CREATE_NO_ENOUGH_COST:1203,//创建俱乐部花费不足
	CLUB_CREATE_NO_PERMISSIONS:1204,//没权限创建俱乐部
	CLUB_CREATE_UNKOWN:1205,//创建失败，数据库问题
	CLUB_GET_LIST_UNKOWN:1207,//获取列表未知错误
	CLUB_GET_INFO_UNKOWN:1208,//获取单个俱乐部信息
	CLUB_GET_MEMBER_COUNT_FAILED:1209,//获取俱乐部成员失败
	CLUB_GET_PLAY_METHOD_UNKONW:1210,//获取玩法列表失败
	CLUB_SET_PLAY_METHOD_UNKONW:1211,//设置俱乐部玩法
	CLUB_APPLY_EXIST:1210,//已在申请列表中
	CLUB_APPLY_UNKONW:1212,//加入俱乐部未知原因
	CLUB_APPLY_MEMBER_EXIST_IN_CLUB:1213,//成员已经在俱乐部中
	CLUB_NOT_EXIST:1214,//俱乐部不存在
	CLUB_GET_MEMBER_UNKONW:1215,//获取成员信息未知错误
	CLUB_GET_APPLY_UNKONW:1216,//获取申请列表错误
	CLUB_APPLY_PERMISSION_DENIED:1217,//权限不足
	CLUB_APPLY_PERMISSION_UNKOWN:1218,//权限不足
	CLUB_MEMBER_INSERT_UNKONW:1219,//插入俱乐部成员错误
	CLUB_APPLY_REMOVE_UNKONW:1220,//删除申请错误
	CLUB_APPLY_NOT_EXIST:1221,//申请人不存在申请列表中
	CLUB_GET_JOIN_CLUB:1222,//获取加入俱乐部列表错误
	CLUB_GET_JOIN_CLUB_LIST_UNKOWN:1223,//获取
	CLUB_GET_INFO_NOT_EXIST:1224,//俱乐部不存在
}

module.exports = errorCode;